const rouletteNumbersData = [
    [{ value: 0, color: 'green', type: null }],
    [
        { value: 3, color: 'red', type: 'impar' },
        { value: 6, color: 'black', type: 'par' },
        { value: 9, color: 'red', type: 'impar' },
        { value: 12, color: 'red', type: 'par' },
        { value: 15, color: 'black', type: 'impar' },
        { value: 18, color: 'red', type: 'par' },
        { value: 21, color: 'red', type: 'impar' },
        { value: 24, color: 'black', type: 'par' },
        { value: 27, color: 'red', type: 'impar' },
        { value: 30, color: 'red', type: 'par' },
        { value: 33, color: 'black', type: 'impar' },
        { value: 36, color: 'red', type: 'par' },
    ],
    [
        { value: 2, color: 'black', type: 'par' },
        { value: 5, color: 'red', type: 'impar' },
        { value: 8, color: 'black', type: 'par' },
        { value: 11, color: 'black', type: 'impar' },
        { value: 14, color: 'red', type: 'par' },
        { value: 17, color: 'black', type: 'impar' },
        { value: 20, color: 'black', type: 'par' },
        { value: 23, color: 'red', type: 'impar' },
        { value: 26, color: 'black', type: 'par' },
        { value: 29, color: 'black', type: 'impar' },
        { value: 32, color: 'red', type: 'par' },
        { value: 35, color: 'black', type: 'impar' },
    ],
    [
        { value: 1, color: 'red', type: 'impar' },
        { value: 4, color: 'black', type: 'par' },
        { value: 7, color: 'red', type: 'impar' },
        { value: 10, color: 'black', type: 'par' },
        { value: 13, color: 'black', type: 'impar' },
        { value: 16, color: 'red', type: 'par' },
        { value: 19, color: 'red', type: 'impar' },
        { value: 22, color: 'black', type: 'par' },
        { value: 25, color: 'red', type: 'impar' },
        { value: 28, color: 'black', type: 'par' },
        { value: 31, color: 'black', type: 'impar' },
        { value: 34, color: 'red', type: 'par' },
    ],
];

export default rouletteNumbersData;
